# Generated by Django 5.2.5 on 2026-04-02 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#ffffff', help_text='Contoh: #f0f0f0 atau lightblue', max_length=50)),
                ('font_family', models.CharField(default='Arial, sans-serif', help_text="Contoh: 'Courier New', Courier, monospace", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('google_name', models.CharField(blank=True, max_length=255, null=True)),
                ('google_picture', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User OAuth Profile',
                'verbose_name_plural': 'User OAuth Profiles',
            },
        ),
    ]
